using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;

namespace Takaragaike.Services
{
    public static class OtpGenerator
    {
        /// <summary>
        /// Generates the OATH-TOTP based on the shared secret key.
        /// </summary>
        /// <param name="key">The shared secret key.</param>
        /// <param name="duration">The effective duration of the OTP.</param>
        /// <returns>The time-based one time password.</returns>
        /// <exception cref="ArgumentNullException">When the key is null.</exception>
        /// <exception cref="ArgumentException">When the key is not valid.</exception>
        public static uint GenerateTotp(byte[] key, int duration = 30)
        {
            // The current UNIX time stamp.
            long unixTimeStamp = DateTimeOffset.UtcNow.ToUnixTimeSeconds() / duration;

            // Converting it into a byte array.

            byte[] byteStamp = BitConverter.GetBytes(unixTimeStamp);

            return GenerateHotp(key, byteStamp);
        }

        /// <summary>
        /// Generates an OATH-HOTP based on the shared key and the counter.
        /// </summary>
        /// <param name="key">The secret shared key.</param>
        /// <param name="counter">The secret counter.</param>
        /// <returns>The HMAC-based one-time password.</returns>
        /// <exception cref="ArgumentNullException">When <paramref name="key"/> and/or <paramref name="counter"/> are/is null.</exception>
        /// <exception cref="ArgumentException">When <paramref name="key"/> is invalid and/or <paramref name="counter"/> is invalid.</exception>
        public static uint GenerateHotp(byte[] key, byte[] counter)
        {
            // The byte array generated by the counter and the secret shared key.
            byte[] bytes = HMACSHA1.HashData(counter, key);

            return (uint)(DynamicTruncation(bytes) % (int)(Math.Pow(10, 6)));
        }

        private static int DynamicTruncation(byte[] bytes)
        {
            ArgumentNullException.ThrowIfNull(bytes);

            if (bytes.Length != 20)
                throw new ArgumentException("Invalid hash.", nameof(bytes));

            int lastByte = bytes.Last();

            int byte1 = (lastByte >> 4) << 4;

            int offset = lastByte - byte1;

            byte[] p = bytes[offset..(offset + 4)];

            return (int)(BitConverter.ToUInt32(p, 0) / (1u << 31));
        }
    }
}
