// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Takaragaike.Contexts;

#nullable disable

namespace Takaragaike.Migrations
{
    [DbContext(typeof(TakaragaikeContext))]
    [Migration("20260329015230_FixedModel")]
    partial class FixedModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("Takaragaike.Models.OtpData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Algorithm")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Counter")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Digits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Issuer")
                        .HasColumnType("TEXT");

                    b.Property<int>("OtpType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SecretKey")
                        .HasColumnType("BLOB");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OtpData");
                });
#pragma warning restore 612, 618
        }
    }
}
